name: Site Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nix_channel:
          - "nixos-unstable"
        run_time:
        # Bun doesn't work now due to "sharp" package failed to build
        #   - bun
          - yarn
        #   - pnpm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          nix_path: nixpkgs=channel:${{matrix.nix_channel}}
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Astro
        env:
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_ALGOLIA_WRITE_KEY: ${{ secrets.GATSBY_ALGOLIA_WRITE_KEY }}
          GATSBY_ALGOLIA_DRY_RUN: true
          GATSBY_ALGOLIA_CONTINUE_ON_FAILURE: true
        run: |
          nix develop --command bash -c "cd site && ${{matrix.run_time}} install"
          nix develop --command bash -c "cd site && ${{matrix.run_time}} build"
